# Generated by Django 4.2 on 2026-05-18 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoFeatureRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("features", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-market_event__timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DemoMarketEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("symbol", models.CharField(default="BTCUSDT", max_length=20)),
                ("mid_price", models.FloatField()),
                ("bid_price", models.FloatField()),
                ("ask_price", models.FloatField()),
                ("spread_bps", models.FloatField()),
                ("source", models.CharField(default="demo_simulator", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DemoTrainingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("model_name", models.CharField(max_length=80)),
                ("dataset_version", models.CharField(max_length=80)),
                ("split_summary", models.CharField(max_length=120)),
                ("pr_auc", models.FloatField()),
                ("f1", models.FloatField()),
                ("precision", models.FloatField()),
                ("recall", models.FloatField()),
                ("lead_time_ms", models.FloatField()),
                ("artifact_path", models.CharField(max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["model_name"],
            },
        ),
        migrations.CreateModel(
            name="DemoPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("model_name", models.CharField(max_length=80)),
                ("risk_score", models.FloatField()),
                ("risk_label", models.CharField(max_length=30)),
                ("explanation", models.CharField(max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "feature_row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="dashboard.demofeaturerow",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="demofeaturerow",
            name="market_event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_rows",
                to="dashboard.demomarketevent",
            ),
        ),
        migrations.CreateModel(
            name="DemoAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("severity", models.CharField(max_length=20)),
                ("message", models.CharField(max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prediction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="dashboard.demoprediction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DemoAgentTrace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("observation", models.TextField()),
                ("risk_evidence", models.JSONField(default=list)),
                ("decision", models.CharField(max_length=160)),
                ("action", models.CharField(max_length=160)),
                ("confidence", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prediction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_traces",
                        to="dashboard.demoprediction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DemoAgentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("agent_id", models.CharField(max_length=40)),
                ("strategy", models.CharField(max_length=80)),
                ("simulated_order", models.CharField(max_length=160)),
                ("simulated_trade", models.CharField(max_length=160)),
                ("side", models.CharField(max_length=8)),
                ("quantity", models.FloatField()),
                ("order_price", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "market_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_events",
                        to="dashboard.demomarketevent",
                    ),
                ),
            ],
            options={
                "ordering": ["-market_event__timestamp"],
            },
        ),
    ]
