# Generated by Django 4.2 on 2026-05-20 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_demofeaturerow_demomarketevent_demotrainingrun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplaySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(default='BTCUSDT', max_length=20)),
                ('scenario_name', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('speed', models.IntegerField(default=1)),
                ('status', models.CharField(default='completed', max_length=20)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulatedAgentTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(max_length=100)),
                ('order_id', models.CharField(max_length=100)),
                ('agent_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('side', models.CharField(max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_trades', to='dashboard.replaysession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SimulatedAgentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100)),
                ('order_id', models.CharField(max_length=100)),
                ('agent_id', models.CharField(max_length=100)),
                ('strategy', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('side', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('remaining_quantity', models.FloatField()),
                ('status', models.CharField(default='new', max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_orders', to='dashboard.replaysession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('severity', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('metric_name', models.CharField(blank=True, max_length=100, null=True)),
                ('metric_value', models.FloatField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='dashboard.replaysession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReplayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('symbol', models.CharField(max_length=20)),
                ('event_type', models.CharField(max_length=50)),
                ('price', models.FloatField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('bid', models.FloatField(blank=True, null=True)),
                ('ask', models.FloatField(blank=True, null=True)),
                ('mid_price', models.FloatField(blank=True, null=True)),
                ('spread', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(max_length=50)),
                ('raw_payload', models.JSONField(default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dashboard.replaysession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReplayCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_index', models.IntegerField(default=0)),
                ('current_timestamp', models.DateTimeField()),
                ('total_events', models.IntegerField(default=0)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cursor', to='dashboard.replaysession')),
            ],
        ),
        migrations.CreateModel(
            name='ModelPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('model_name', models.CharField(max_length=100)),
                ('risk_score', models.FloatField()),
                ('risk_label', models.CharField(max_length=50)),
                ('explanation', models.TextField()),
                ('confidence', models.FloatField(default=1.0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='dashboard.replaysession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FeatureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('features', models.JSONField(default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_snapshots', to='dashboard.replaysession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DecisionAuditTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('observation', models.TextField()),
                ('feature_evidence', models.JSONField(default=dict)),
                ('model_interpretation', models.TextField()),
                ('policy_decision', models.CharField(max_length=100)),
                ('recommended_control', models.CharField(max_length=200)),
                ('linked_event_id', models.CharField(blank=True, default='', max_length=100)),
                ('linked_prediction_id', models.CharField(blank=True, default='', max_length=100)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_traces', to='dashboard.replaysession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
