# Generated by Django 4.2 on 2026-05-20 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_replayevent_real_market_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRunRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=100)),
                ('agent_name', models.CharField(max_length=100)),
                ('goal', models.CharField(max_length=200)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('duration_ms', models.FloatField()),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True, default='')),
                ('output', models.JSONField(default=dict)),
                ('linked_artifacts', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='ImmuneLoopRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loop_id', models.CharField(max_length=100, unique=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('duration_ms', models.FloatField()),
                ('difficulty', models.CharField(default='medium', max_length=20)),
                ('aggregate_posture', models.CharField(default='no_action', max_length=40)),
                ('proposal_name', models.CharField(blank=True, default='', max_length=200)),
                ('new_memory_count', models.IntegerField(default=0)),
                ('alert_count', models.IntegerField(default=0)),
                ('case_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ImmuneMemoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_id', models.CharField(max_length=120, unique=True)),
                ('threat_name', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('scenario_source', models.CharField(max_length=200)),
                ('key_signals', models.JSONField(default=list)),
                ('best_detector', models.CharField(max_length=120)),
                ('failed_detector', models.CharField(max_length=120)),
                ('recommended_detector', models.CharField(max_length=120)),
                ('example_case_id', models.CharField(blank=True, default='', max_length=120)),
                ('novelty_score', models.FloatField(default=0.0)),
                ('times_seen', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelPromotionDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_id', models.CharField(max_length=120, unique=True)),
                ('candidate_model', models.CharField(max_length=120)),
                ('incumbent_model', models.CharField(blank=True, default='', max_length=120)),
                ('verdict', models.CharField(max_length=40)),
                ('rationale', models.TextField(blank=True, default='')),
                ('metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioProposalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('base_scenario', models.CharField(max_length=100)),
                ('cover_scenario', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_attack', models.CharField(max_length=200)),
                ('evasion_strategy', models.CharField(blank=True, default='', max_length=400)),
                ('difficulty', models.CharField(default='medium', max_length=20)),
                ('features', models.JSONField(default=dict)),
                ('rationale', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='dashboard.immunelooprun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyDecisionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_id', models.CharField(max_length=120, unique=True)),
                ('case_id', models.CharField(max_length=120)),
                ('recommended_action', models.CharField(max_length=60)),
                ('severity', models.CharField(max_length=20)),
                ('rationale', models.TextField()),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_decisions', to='dashboard.immunelooprun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationCaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=120, unique=True)),
                ('alert_id', models.CharField(max_length=120)),
                ('suspected_behavior', models.CharField(max_length=160)),
                ('severity', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('observation', models.TextField()),
                ('feature_evidence', models.JSONField(default=dict)),
                ('model_evidence', models.JSONField(default=dict)),
                ('timeline', models.JSONField(default=list)),
                ('matched_rules', models.JSONField(default=list)),
                ('recommended_next_step', models.CharField(max_length=400)),
                ('explanation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='dashboard.immunelooprun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentToolCallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(max_length=160)),
                ('arguments', models.JSONField(default=dict)),
                ('duration_ms', models.FloatField(default=0.0)),
                ('result_summary', models.CharField(blank=True, default='', max_length=400)),
                ('occurred_at', models.DateTimeField()),
                ('agent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='dashboard.agentrunrecord')),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
        migrations.AddField(
            model_name='agentrunrecord',
            name='loop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='dashboard.immunelooprun'),
        ),
        migrations.CreateModel(
            name='AgentDecisionTraceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=200)),
                ('observation', models.TextField()),
                ('decision', models.CharField(max_length=200)),
                ('confidence', models.FloatField(default=0.5)),
                ('evidence', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('agent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_traces', to='dashboard.agentrunrecord')),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
    ]
