# Generated by Codex on 2026-06-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_agentic_loop_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoredFillDecision',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('decision_id', models.CharField(max_length=180, unique=True)),
                ('coin', models.CharField(max_length=30)),
                ('ts_ms', models.FloatField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('px', models.FloatField()),
                ('sz', models.FloatField()),
                ('side', models.CharField(blank=True, default='', max_length=20)),
                ('maker_side', models.IntegerField()),
                ('model_name', models.CharField(db_index=True, max_length=200)),
                ('raw_score', models.FloatField()),
                ('calibrated_score', models.FloatField()),
                ('decision_threshold', models.FloatField(blank=True, null=True)),
                ('action', models.CharField(db_index=True, max_length=40)),
                ('severity', models.CharField(db_index=True, max_length=20)),
                ('markout_bps', models.FloatField(blank=True, null=True)),
                ('toxic', models.BooleanField(blank=True, null=True)),
                ('tid', models.BigIntegerField(blank=True, null=True)),
                ('oid', models.BigIntegerField(blank=True, null=True)),
                ('feature_values', models.JSONField(default=dict)),
                ('top_features', models.JSONField(default=list)),
                ('source_path', models.CharField(blank=True, default='', max_length=500)),
                ('scored_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
