# Generated by Codex on 2026-06-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_scoredfilldecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoredfilldecision',
            name='loop',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='scored_fill_decisions',
                to='dashboard.immunelooprun',
            ),
        ),
        migrations.AddField(
            model_name='scoredfilldecision',
            name='case_id',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='scoredfilldecision',
            name='policy_decision_id',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='scoredfilldecision',
            name='recommended_action',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
