# Generated by Codex on 2026-06-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_scoredfilldecision_loop_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigationcaserecord',
            name='case_id',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='policydecisionrecord',
            name='decision_id',
            field=models.CharField(db_index=True, max_length=120),
        ),
    ]
