# Generated by Codex on 2026-06-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_loop_scoped_agentic_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoredFillDecisionLink',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('case_id', models.CharField(db_index=True, max_length=160)),
                ('policy_decision_id', models.CharField(blank=True, default='', max_length=160)),
                ('recommended_action', models.CharField(blank=True, default='', max_length=80)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                (
                    'decision',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='loop_links',
                        to='dashboard.scoredfilldecision',
                    ),
                ),
                (
                    'loop',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='scored_fill_links',
                        to='dashboard.immunelooprun',
                    ),
                ),
            ],
            options={
                'ordering': ['-linked_at'],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('decision', 'loop', 'case_id'),
                        name='uniq_scored_fill_loop_case',
                    ),
                ],
            },
        ),
    ]
