# Generated by Codex on 2026-06-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_scoredfilldecisionlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoredFillRefreshRun',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('trigger', models.CharField(db_index=True, default='manual', max_length=30)),
                ('source_path', models.CharField(blank=True, default='', max_length=500)),
                ('requested_limit', models.IntegerField(default=0)),
                ('refreshed_count', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
