# Generated by Codex on 2026-06-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_scoredfillrefreshrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='HyperliquidBackfillJob',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('job_id', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('trigger', models.CharField(db_index=True, default='manual', max_length=30)),
                ('coin', models.CharField(db_index=True, max_length=30)),
                ('date', models.CharField(db_index=True, max_length=8)),
                ('hours', models.JSONField(default=list)),
                ('fill_suffixes', models.JSONField(default=list)),
                ('lake_root', models.CharField(default='data/hyperliquid', max_length=500)),
                ('include_asset_ctxs', models.BooleanField(default=True)),
                ('refresh_decisions', models.BooleanField(default=True)),
                ('dry_run', models.BooleanField(default=False)),
                ('book_snapshots', models.IntegerField(default=0)),
                ('asset_contexts', models.IntegerField(default=0)),
                ('fills', models.IntegerField(default=0)),
                ('gold_rows', models.IntegerField(default=0)),
                ('training_rows', models.IntegerField(default=0)),
                ('writes', models.JSONField(default=list)),
                ('refresh_run_id', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
